FROM golang:1.15-alpine

RUN apk update && apk add --no-cache git mercurial openssh
RUN apk add ca-certificates tzdata

RUN go get github.com/go-delve/delve/cmd/dlv

WORKDIR /app

COPY zoneinfo.zip /app/zoneinfo.zip
ENV ZONEINFO /app/zoneinfo.zip

COPY ./build/service_kyc /app/service_kyc

ENTRYPOINT ["/app/service_kyc"]